"use strict";

// Motor genérico de conciliación de dos archivos Excel.
// Uso:
// node scripts/conciliar-bases.js --principal=a.xlsx --secundaria=b.xlsx --config=config.js
// Opciones: --salida=conciliado.xlsx --reporte=reporte.xlsx --json=resumen|hallazgos|completo|ninguno --limite=20

const fs=require("fs"),path=require("path"),XLSX=require("xlsx");
function args(a){const o={};for(const x of a){if(!x.startsWith("--"))continue;const p=x.slice(2).split(/=(.*)/s);o[p[0].toLowerCase()]=p[1]===undefined?"true":p[1]}return o}
function ayuda(){console.log(`Uso: node scripts/conciliar-bases.js --principal=<xlsx> --secundaria=<xlsx> --config=<js> [opciones]\n--salida --reporte --json --limite --simular --estricto`)}
const o=args(process.argv.slice(2));if(o.ayuda==="true"){ayuda();process.exit(0)}if(!o.principal||!o.secundaria) {ayuda();process.exit(1)}
const principal=path.resolve(o.principal),secundaria=path.resolve(o.secundaria),salida=path.resolve(o.salida||"base-conciliada.xlsx"),reporte=path.resolve(o.reporte||"reporte-conciliacion.xlsx");
for(const f of[principal,secundaria])if(!fs.existsSync(f))throw new Error(`No existe: ${f}`);
let config={};if(o.config){const c=path.resolve(o.config);if(!fs.existsSync(c))throw new Error(`No existe config: ${c}`);config=require(c)}
const modo=(o.json||"resumen").toLowerCase(),limite=Number(o.limite??20),simular=o.simular==="true",estricto=o.estricto==="true";
if(!["resumen","hallazgos","completo","ninguno"].includes(modo)||!Number.isInteger(limite)||limite<0)throw new Error("Opciones inválidas");
const vacio=v=>v===null||v===undefined||(typeof v==="string"&&!v.trim());const texto=v=>vacio(v)?"":String(v).trim().replace(/\s+/g," ");const numero=v=>typeof v==="number"&&Number.isFinite(v)?v:(typeof v==="string"&&v.trim()&&Number.isFinite(Number(v.trim().replace(",",".")))?Number(v.trim().replace(",",".")):null);
const fecha=v=>{if(vacio(v))return"";if(typeof v==="number"){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,"0")}-${String(d.d).padStart(2,"0")}`:""}return String(v).trim()};const hora=v=>{if(vacio(v))return"";if(typeof v==="number"){let s=Math.round((v-Math.floor(v))*86400);return[Math.floor(s/3600),Math.floor((s%3600)/60),s%60].map(n=>String(n).padStart(2,"0")).join(":")}return String(v).trim()};
const utilidades={vacio,texto,numero,fecha,hora};const comp=v=>{if(vacio(v))return"V:";const n=numero(v);return n!==null?`N:${n}`:`T:${texto(v).toLowerCase()}`};
const normaliza=(r)=>{const x={...r};for(const[c,n]of Object.entries(config.normalizadores||{}))x[c]=typeof n==="function"?n({valor:x[c],registro:x,utilidades}):n==="fecha"?fecha(x[c]):n==="hora"?hora(x[c]):n==="texto"?texto(x[c]):n==="numero"?numero(x[c]):x[c];return x};
const hojaP=config.hojaPrincipal||config.hoja||null,hojaS=config.hojaSecundaria||config.hoja||null;
function carga(f,origen,hn){const wb=XLSX.readFile(f,{cellDates:false});const h=hn||wb.SheetNames[0];if(!wb.Sheets[h])throw new Error(`No existe hoja ${h} en ${f}`);return XLSX.utils.sheet_to_json(wb.Sheets[h],{defval:null,raw:true}).map((r,i)=>({origen,fila:i+2,registro:normaliza(r)}))}
const A=carga(principal,"Principal",hojaP),B=carga(secundaria,"Secundaria",hojaS);const colsA=[...new Set(A.flatMap(i=>Object.keys(i.registro)))],colsB=[...new Set(B.flatMap(i=>Object.keys(i.registro)))],comunes=config.columnasComparacion||colsA.filter(c=>colsB.includes(c)),salidaCols=[...colsA,...colsB.filter(c=>!colsA.includes(c))];
const claveCampos=config.clave||comunes;const clave=r=>typeof config.construirClave==="function"?String(config.construirClave({registro:r,utilidades})):claveCampos.map(c=>comp(r[c])).join("|");const equivalentes=(a,b)=>comunes.every(c=>comp(a[c])===comp(b[c]));
function excluir(item){for(const regla of config.exclusiones||[]){if(regla.cuando({registro:item.registro,fila:item.fila,origen:item.origen,utilidades}))return regla}return null}
function grupos(items){const m=new Map();for(const i of items){i.clave=clave(i.registro);if(!m.has(i.clave))m.set(i.clave,[]);m.get(i.clave).push(i)}return m}
const gA=grupos(A),gB=grupos(B),claves=new Set([...gA.keys(),...gB.keys()]);const coincidencias=[],soloPrincipal=[],soloSecundaria=[],excluidos=[],conflictos=[],diferencias=[],agregados=[];const conciliados=A.map(i=>({...i,motivo:"Base principal"}));
for(const k of claves){const aa=gA.get(k)||[],bb=gB.get(k)||[];if(!bb.length){soloPrincipal.push(...aa.map(i=>({Clave:k,Fila:i.fila,...i.registro})));continue}if(!aa.length){for(const i of bb){soloSecundaria.push({Clave:k,Fila:i.fila,...i.registro});const ex=excluir(i);if(ex){excluidos.push({Clave:k,Fila:i.fila,Regla:ex.id||null,Motivo:ex.motivo||"Exclusión configurada",Registro:JSON.stringify(i.registro)});continue}agregados.push(i);conciliados.push({...i,motivo:"Exclusivo secundaria"})}continue}const ua=new Set(),ub=new Set();for(let i=0;i<aa.length;i++)for(let j=0;j<bb.length;j++){if(ub.has(j)||!equivalentes(aa[i].registro,bb[j].registro))continue;ua.add(i);ub.add(j);coincidencias.push({Clave:k,FilaPrincipal:aa[i].fila,FilaSecundaria:bb[j].fila});break}const ra=aa.filter((_,i)=>!ua.has(i)),rb=bb.filter((_,i)=>!ub.has(i));for(let i=0;i<Math.max(ra.length,rb.length);i++){const a=ra[i],b=rb[i];if(a&&b)for(const c of comunes)if(comp(a.registro[c])!==comp(b.registro[c]))diferencias.push({Clave:k,FilaPrincipal:a.fila,FilaSecundaria:b.fila,Campo:c,ValorPrincipal:a.registro[c],ValorSecundaria:b.registro[c]});conflictos.push({Clave:k,FilaPrincipal:a?.fila??null,FilaSecundaria:b?.fila??null,RequiereRevision:"Sí"});if(b){const ex=excluir(b);if(ex)excluidos.push({Clave:k,Fila:b.fila,Regla:ex.id||null,Motivo:ex.motivo,Registro:JSON.stringify(b.registro)});else{agregados.push(b);conciliados.push({...b,motivo:"Conflicto secundaria"})}}}}
if(estricto&&conflictos.length)throw new Error("Modo estricto: existen conflictos");
if(config.ordenar!==false)conciliados.sort((a,b)=>clave(a.registro).localeCompare(clave(b.registro),"es",{numeric:true})||a.fila-b.fila);
const registros=conciliados.map(i=>Object.fromEntries(salidaCols.map(c=>[c,i.registro[c]??null]))),traza=conciliados.map((i,n)=>({FilaSalida:n+2,Origen:i.origen,FilaOrigen:i.fila,Clave:clave(i.registro),Motivo:i.motivo}));
if(registros.length!==A.length+agregados.length)throw new Error("Falló control de integridad");
const resumen={principal:path.basename(principal),secundaria:path.basename(secundaria),totalPrincipal:A.length,totalSecundaria:B.length,paresCoincidentes:coincidencias.length,soloPrincipal:soloPrincipal.length,soloSecundaria:soloSecundaria.length,excluidos:excluidos.length,conflictos:conflictos.length,agregados:agregados.length,totalConciliado:registros.length,formula:`${A.length} + ${agregados.length} = ${registros.length}`};
function add(w,n,d,h){const x=d.length?d:[{Resultado:"Sin registros"}],s=XLSX.utils.json_to_sheet(x,h?{header:h}:undefined);XLSX.utils.book_append_sheet(w,s,n)}
if(!simular){const w=XLSX.utils.book_new();add(w,config.hojaSalida||config.hoja||"Datos",registros,salidaCols);add(w,"Trazabilidad",traza);XLSX.writeFile(w,salida);const r=XLSX.utils.book_new();add(r,"Resumen",Object.entries(resumen).map(([Indicador,Valor])=>({Indicador,Valor})));add(r,"SoloPrincipal",soloPrincipal);add(r,"SoloSecundaria",soloSecundaria);add(r,"Excluidos",excluidos);add(r,"Coincidencias",coincidencias);add(r,"Conflictos",conflictos);add(r,"Diferencias",diferencias);add(r,"Trazabilidad",traza);XLSX.writeFile(r,reporte)}
const resultado={metadatos:{fechaISO:new Date().toISOString(),principal,secundaria,salida,reporte,simular,originalesModificados:false},resumen,estructura:{columnasPrincipal:colsA,columnasSecundaria:colsB,columnasComunes:comunes,columnasSalida:salidaCols},hallazgos:{soloPrincipal,soloSecundaria,excluidos,coincidencias,conflictos,diferencias,trazabilidadAgregados:traza.filter(x=>x.Origen==="Secundaria")}};
const lim=v=>Array.isArray(v)&&limite&&v.length>limite?{total:v.length,mostrados:limite,omitidos:v.length-limite,elementos:v.slice(0,limite)}:Array.isArray(v)?v:(v&&typeof v==="object"?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,lim(x)])):v);let con=null;if(modo==="resumen")con={metadatos:resultado.metadatos,resumen,estructura:resultado.estructura};if(modo==="hallazgos"||modo==="completo")con=lim(resultado);console.log("\nCONCILIACIÓN FINALIZADA",resumen);if(!simular)console.log(`Salida: ${salida}\nReporte: ${reporte}`);if(con){console.log("\n================ INICIO JSON ================");console.log(JSON.stringify(con,null,2));console.log("================= FIN JSON =================")}